version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
      - echo Fri Jan 24 21:11:53 UTC 2020
      - pwd
      - ls
      #- |
      #  env | grep 'WEBHOOK' || echo Fri Jan 24 21:11:53 UTC 2020
      # - git clone https://github.com/gitpenvij/casePipeline.git /tmp
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - echo Fri Jan 24 21:11:53 UTC 2020
      # - command
      # - command
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path

