version: 0.2

env:
  exported-variables:
  - ImageURI
  - ImageDigest
  - ImageTag
  - RegistryId
  # variables:
  #    key: "value"
  #    key: "value"
  # parameter-store:
  #    key: "value"
  #    key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
      - echo Fri Jan 24 22:49:00 UTC 2020
      - pwd
      - ls
      #- |
      #  env | grep 'WEBHOOK' || echo Fri Jan 24 22:49:00 UTC 2020
      # - git clone https://github.com/gitpenvij/casePipeline.git /tmp
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - |
        nohup vmstat 2> vmstat.out &
      - sleep 6s
      - echo Fri Jan 24 22:49:00 UTC 2020
      - printenv | egrep '^GIT.*|^CANDIDATE_ID.*'
      - cat vmstat.out
      - ImageURI='123213232.docker-priv.test.com/nginx'
      - ImageDigest='sha256@aabdskkh1233h2lkskldhl23h2l1k31skds899ufg'
      - |
        ImageTag=`echo $GIT_COMMIT_ID | cut -c 1-8`
      - RegistryId=123213232
      # - command
      # - command
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path

