version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  pre_build:
    commands:
      - echo Wed May 15 21:21:34 UTC 2019
      - pwd
      - ls
      - env | grep 'WEBHOOK'
      # - git clone https://github.com/gitpenvij/casePipeline.git /tmp
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - bash ./scripts/build.sh
      # - command
      # - command
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path

